version: '3.1'
services:
  db:
    image: mysql
    container_name: ordermysqlprod
    environment:
      MYSQL_ROOT_PASSWORD: restaurants
    ports:
      - "3306:3306"
    volumes:
      - vitorhr10_data:/var/lib/mysql

  web:
    image: nginx
    container_name: ordernginxprod
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

volumes:
  vitorhr10_data: